// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: v1/train_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Train struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From      string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To        string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Capacity  int32  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Departure string `protobuf:"bytes,5,opt,name=departure,proto3" json:"departure,omitempty"`
	Arrival   string `protobuf:"bytes,6,opt,name=arrival,proto3" json:"arrival,omitempty"`
}

func (x *Train) Reset() {
	*x = Train{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_train_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Train) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Train) ProtoMessage() {}

func (x *Train) ProtoReflect() protoreflect.Message {
	mi := &file_v1_train_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Train.ProtoReflect.Descriptor instead.
func (*Train) Descriptor() ([]byte, []int) {
	return file_v1_train_service_proto_rawDescGZIP(), []int{0}
}

func (x *Train) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Train) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Train) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Train) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Train) GetDeparture() string {
	if x != nil {
		return x.Departure
	}
	return ""
}

func (x *Train) GetArrival() string {
	if x != nil {
		return x.Arrival
	}
	return ""
}

type ListTrainsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListTrainsRequest) Reset() {
	*x = ListTrainsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_train_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTrainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrainsRequest) ProtoMessage() {}

func (x *ListTrainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_train_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrainsRequest.ProtoReflect.Descriptor instead.
func (*ListTrainsRequest) Descriptor() ([]byte, []int) {
	return file_v1_train_service_proto_rawDescGZIP(), []int{1}
}

type ListTrainsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trains []*Train `protobuf:"bytes,1,rep,name=trains,proto3" json:"trains,omitempty"`
}

func (x *ListTrainsResponse) Reset() {
	*x = ListTrainsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_train_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTrainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrainsResponse) ProtoMessage() {}

func (x *ListTrainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_train_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrainsResponse.ProtoReflect.Descriptor instead.
func (*ListTrainsResponse) Descriptor() ([]byte, []int) {
	return file_v1_train_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListTrainsResponse) GetTrains() []*Train {
	if x != nil {
		return x.Trains
	}
	return nil
}

type CreateTrainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From      string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To        string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Capacity  int32  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Departure string `protobuf:"bytes,5,opt,name=departure,proto3" json:"departure,omitempty"`
	Arrival   string `protobuf:"bytes,6,opt,name=arrival,proto3" json:"arrival,omitempty"`
}

func (x *CreateTrainRequest) Reset() {
	*x = CreateTrainRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_train_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrainRequest) ProtoMessage() {}

func (x *CreateTrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_train_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrainRequest.ProtoReflect.Descriptor instead.
func (*CreateTrainRequest) Descriptor() ([]byte, []int) {
	return file_v1_train_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTrainRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateTrainRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *CreateTrainRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *CreateTrainRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *CreateTrainRequest) GetDeparture() string {
	if x != nil {
		return x.Departure
	}
	return ""
}

func (x *CreateTrainRequest) GetArrival() string {
	if x != nil {
		return x.Arrival
	}
	return ""
}

type CreateTrainResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Train *Train `protobuf:"bytes,1,opt,name=train,proto3" json:"train,omitempty"`
}

func (x *CreateTrainResponse) Reset() {
	*x = CreateTrainResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_train_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrainResponse) ProtoMessage() {}

func (x *CreateTrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_train_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrainResponse.ProtoReflect.Descriptor instead.
func (*CreateTrainResponse) Descriptor() ([]byte, []int) {
	return file_v1_train_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTrainResponse) GetTrain() *Train {
	if x != nil {
		return x.Train
	}
	return nil
}

var File_v1_train_service_proto protoreflect.FileDescriptor

var file_v1_train_service_proto_rawDesc = []byte{
	0x0a, 0x16, 0x76, 0x31, 0x2f, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x73,
	0x2e, 0x76, 0x31, 0x22, 0x8f, 0x01, 0x0a, 0x05, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74,
	0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12, 0x1c, 0x0a,
	0x09, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x72,
	0x72, 0x69, 0x76, 0x61, 0x6c, 0x22, 0x13, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x72, 0x61,
	0x69, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3e, 0x0a, 0x12, 0x4c, 0x69,
	0x73, 0x74, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x28, 0x0a, 0x06, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61,
	0x69, 0x6e, 0x52, 0x06, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x73, 0x22, 0x9c, 0x01, 0x0a, 0x12, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74,
	0x79, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x22, 0x3d, 0x0a, 0x13, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x26, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x69,
	0x6e, 0x52, 0x05, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x32, 0xa8, 0x01, 0x0a, 0x0d, 0x54, 0x72, 0x61,
	0x69, 0x6e, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x0b, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x12, 0x1d, 0x2e, 0x74, 0x72, 0x61, 0x69,
	0x6e, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x74, 0x72, 0x61, 0x69, 0x6e,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74,
	0x54, 0x72, 0x61, 0x69, 0x6e, 0x73, 0x12, 0x1c, 0x2e, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x61, 0x73, 0x66, 0x6f, 0x75, 0x72, 0x63, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d,
	0x74, 0x72, 0x61, 0x69, 0x6e, 0x2f, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x73, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_train_service_proto_rawDescOnce sync.Once
	file_v1_train_service_proto_rawDescData = file_v1_train_service_proto_rawDesc
)

func file_v1_train_service_proto_rawDescGZIP() []byte {
	file_v1_train_service_proto_rawDescOnce.Do(func() {
		file_v1_train_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_train_service_proto_rawDescData)
	})
	return file_v1_train_service_proto_rawDescData
}

var file_v1_train_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1_train_service_proto_goTypes = []interface{}{
	(*Train)(nil),               // 0: trains.v1.Train
	(*ListTrainsRequest)(nil),   // 1: trains.v1.ListTrainsRequest
	(*ListTrainsResponse)(nil),  // 2: trains.v1.ListTrainsResponse
	(*CreateTrainRequest)(nil),  // 3: trains.v1.CreateTrainRequest
	(*CreateTrainResponse)(nil), // 4: trains.v1.CreateTrainResponse
}
var file_v1_train_service_proto_depIdxs = []int32{
	0, // 0: trains.v1.ListTrainsResponse.trains:type_name -> trains.v1.Train
	0, // 1: trains.v1.CreateTrainResponse.train:type_name -> trains.v1.Train
	3, // 2: trains.v1.TrainsService.CreateTrain:input_type -> trains.v1.CreateTrainRequest
	1, // 3: trains.v1.TrainsService.ListTrains:input_type -> trains.v1.ListTrainsRequest
	4, // 4: trains.v1.TrainsService.CreateTrain:output_type -> trains.v1.CreateTrainResponse
	2, // 5: trains.v1.TrainsService.ListTrains:output_type -> trains.v1.ListTrainsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_train_service_proto_init() }
func file_v1_train_service_proto_init() {
	if File_v1_train_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_train_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Train); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_train_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTrainsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_train_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTrainsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_train_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTrainRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_train_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTrainResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_train_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_train_service_proto_goTypes,
		DependencyIndexes: file_v1_train_service_proto_depIdxs,
		MessageInfos:      file_v1_train_service_proto_msgTypes,
	}.Build()
	File_v1_train_service_proto = out.File
	file_v1_train_service_proto_rawDesc = nil
	file_v1_train_service_proto_goTypes = nil
	file_v1_train_service_proto_depIdxs = nil
}
