// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: v1/passenger_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Passenger struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Passenger) Reset() {
	*x = Passenger{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_passenger_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Passenger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Passenger) ProtoMessage() {}

func (x *Passenger) ProtoReflect() protoreflect.Message {
	mi := &file_v1_passenger_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Passenger.ProtoReflect.Descriptor instead.
func (*Passenger) Descriptor() ([]byte, []int) {
	return file_v1_passenger_service_proto_rawDescGZIP(), []int{0}
}

func (x *Passenger) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Passenger) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListPassengersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPassengersRequest) Reset() {
	*x = ListPassengersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_passenger_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPassengersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPassengersRequest) ProtoMessage() {}

func (x *ListPassengersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_passenger_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPassengersRequest.ProtoReflect.Descriptor instead.
func (*ListPassengersRequest) Descriptor() ([]byte, []int) {
	return file_v1_passenger_service_proto_rawDescGZIP(), []int{1}
}

type ListPassengersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Passengers []*Passenger `protobuf:"bytes,1,rep,name=passengers,proto3" json:"passengers,omitempty"`
}

func (x *ListPassengersResponse) Reset() {
	*x = ListPassengersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_passenger_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPassengersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPassengersResponse) ProtoMessage() {}

func (x *ListPassengersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_passenger_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPassengersResponse.ProtoReflect.Descriptor instead.
func (*ListPassengersResponse) Descriptor() ([]byte, []int) {
	return file_v1_passenger_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListPassengersResponse) GetPassengers() []*Passenger {
	if x != nil {
		return x.Passengers
	}
	return nil
}

type CreatePassengerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreatePassengerRequest) Reset() {
	*x = CreatePassengerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_passenger_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePassengerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePassengerRequest) ProtoMessage() {}

func (x *CreatePassengerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_passenger_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePassengerRequest.ProtoReflect.Descriptor instead.
func (*CreatePassengerRequest) Descriptor() ([]byte, []int) {
	return file_v1_passenger_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePassengerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreatePassengerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreatePassengerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Passenger *Passenger `protobuf:"bytes,1,opt,name=passenger,proto3" json:"passenger,omitempty"`
}

func (x *CreatePassengerResponse) Reset() {
	*x = CreatePassengerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_passenger_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePassengerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePassengerResponse) ProtoMessage() {}

func (x *CreatePassengerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_passenger_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePassengerResponse.ProtoReflect.Descriptor instead.
func (*CreatePassengerResponse) Descriptor() ([]byte, []int) {
	return file_v1_passenger_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePassengerResponse) GetPassenger() *Passenger {
	if x != nil {
		return x.Passenger
	}
	return nil
}

var File_v1_passenger_service_proto protoreflect.FileDescriptor

var file_v1_passenger_service_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70, 0x61,
	0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x2f, 0x0a, 0x09, 0x50,
	0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x17, 0x0a, 0x15,
	0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x52, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x73,
	0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x38, 0x0a, 0x0a, 0x70, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x52, 0x0a, 0x70,
	0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x73, 0x22, 0x3c, 0x0a, 0x16, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x51, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x36, 0x0a, 0x09, 0x70, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65,
	0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x52,
	0x09, 0x70, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x32, 0xd4, 0x01, 0x0a, 0x11, 0x50,
	0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x60, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x65, 0x6e,
	0x67, 0x65, 0x72, 0x12, 0x25, 0x2e, 0x70, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x65, 0x6e,
	0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x70, 0x61, 0x73,
	0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x5d, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x73, 0x73, 0x65, 0x6e,
	0x67, 0x65, 0x72, 0x73, 0x12, 0x24, 0x2e, 0x70, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x70, 0x61, 0x73,
	0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50,
	0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x61, 0x73, 0x66, 0x6f, 0x75, 0x72, 0x63, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x2f, 0x70, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x73, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_passenger_service_proto_rawDescOnce sync.Once
	file_v1_passenger_service_proto_rawDescData = file_v1_passenger_service_proto_rawDesc
)

func file_v1_passenger_service_proto_rawDescGZIP() []byte {
	file_v1_passenger_service_proto_rawDescOnce.Do(func() {
		file_v1_passenger_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_passenger_service_proto_rawDescData)
	})
	return file_v1_passenger_service_proto_rawDescData
}

var file_v1_passenger_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1_passenger_service_proto_goTypes = []interface{}{
	(*Passenger)(nil),               // 0: passengers.v1.Passenger
	(*ListPassengersRequest)(nil),   // 1: passengers.v1.ListPassengersRequest
	(*ListPassengersResponse)(nil),  // 2: passengers.v1.ListPassengersResponse
	(*CreatePassengerRequest)(nil),  // 3: passengers.v1.CreatePassengerRequest
	(*CreatePassengerResponse)(nil), // 4: passengers.v1.CreatePassengerResponse
}
var file_v1_passenger_service_proto_depIdxs = []int32{
	0, // 0: passengers.v1.ListPassengersResponse.passengers:type_name -> passengers.v1.Passenger
	0, // 1: passengers.v1.CreatePassengerResponse.passenger:type_name -> passengers.v1.Passenger
	3, // 2: passengers.v1.PassengersService.CreatePassenger:input_type -> passengers.v1.CreatePassengerRequest
	1, // 3: passengers.v1.PassengersService.ListPassengers:input_type -> passengers.v1.ListPassengersRequest
	4, // 4: passengers.v1.PassengersService.CreatePassenger:output_type -> passengers.v1.CreatePassengerResponse
	2, // 5: passengers.v1.PassengersService.ListPassengers:output_type -> passengers.v1.ListPassengersResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_passenger_service_proto_init() }
func file_v1_passenger_service_proto_init() {
	if File_v1_passenger_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_passenger_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Passenger); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_passenger_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPassengersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_passenger_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPassengersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_passenger_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePassengerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_passenger_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePassengerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_passenger_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_passenger_service_proto_goTypes,
		DependencyIndexes: file_v1_passenger_service_proto_depIdxs,
		MessageInfos:      file_v1_passenger_service_proto_msgTypes,
	}.Build()
	File_v1_passenger_service_proto = out.File
	file_v1_passenger_service_proto_rawDesc = nil
	file_v1_passenger_service_proto_goTypes = nil
	file_v1_passenger_service_proto_depIdxs = nil
}
